namespace UnityCraft.Blocks
{
    public enum BlockTypes : byte
    {
        /// <summary>
        /// Default, empty state/block.
        /// </summary>
        Air = 0,
        Stone = 1,
        Grass = 2,
        Dirt = 3,
        Cobblestone = 4,
        Planks = 5,
        Sapling = 6,
        Bedrock = 7,
        Water = 8,
        StillWater = 9,
        Lava = 10,
        StillLava = 11,
        Sand = 12,
        Gravel = 13,
        GoldOre = 14,
        IronOre = 15,
        CoalOre = 16,
        Wood = 17,
        Leaves = 18,
        Sponge = 19,
        Glass = 20,
        ClothRed = 21,
        ClothOrange = 22,
        ClothYellow = 23,
        ClothChartreuse = 24,
        ClothGreen = 25,
        ClothSpringGreen = 26,
        ClothCyan = 27,
        ClothCapri = 28,
        ClothUltramarine = 29,
        ClothViolet = 30,
        ClothPurple = 31,
        ClothMagenta = 32,
        ClothRose = 33,
        ClothDarkGray = 34,
        ClothLightGray = 35,
        ClothWhite = 36,
        Dandelion = 37,
        Rose = 38,
        BrownMushroom = 39,
        RedMushroom = 40,
        GoldBlock = 41,
        IronBlock = 42,
        DoubleSlab = 43,
        Slab = 44,
        Bricks = 45,
        TNT = 46,
        Bookshelf = 47,
        MossyCobblestone = 48,
        Obsidian = 49,
        Torch = 50,
        Fire = 51,
        InfiniteWater = 52,
        InfiniteLava = 53,
        Chest = 54,
        Cog = 55,
        DiamondOre = 56,
        DiamondBlock = 57,
        CraftingTable = 58,
        Crops = 59,
        Farmland = 60,
        Furnace = 61,
        LitFurnace = 62,
        Invalid = 255
    }
}